#!/usr/bin/env python3

import argparse
import os
import sys
from pathlib import Path

TEMPLATES = {
    "dockerfile_python": """# Auto-generated by Chrono Manifest Generator (Phase 7)
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies for math/GPU libs
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libgomp1 \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Default port for Cloud Run/Vulcan bursting
EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
""",
    "dockerfile_godot": """# Auto-generated by Chrono Manifest Generator (Phase 7)
FROM barichello/godot-ci:4.3 AS builder

WORKDIR /app
COPY . .
RUN mkdir -p build/linux && \\
    godot --headless --export-release "Linux/X11" build/linux/simulation.x86_64

FROM ubuntu:jammy
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libxcursor1 libxinerama1 libxrandr2 libxi6 libgl1-mesa-dri libvulkan1 \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/build/linux/ .

CMD ["./simulation.x86_64", "--headless"]
""",
    "cloud_run_yaml": """# Vulcan (Fabrication) Bursting Service
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {name}
  labels:
    cloud.googleapis.com/location: {region}
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - image: {image_url}
        resources:
          limits:
            cpu: "{cpu}"
            memory: "{memory}"
            # GPU support if requested in Sovereign Cloud
            # nvidia.com/gpu: "1"
        ports:
        - containerPort: 8080
""",
    "k8s_yaml": """# Sentinel Swarm Pod Template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}-sentinel
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - name: simulation
        image: {image_url}
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
"""
}

def main():
    parser = argparse.ArgumentParser(description="Chrono Manifest Generator for Sovereign Cloud Upgrade.")
    parser.add_argument("--name", required=True, help="Name of the simulation logic component")
    parser.add_argument("--type", choices=["python", "godot"], default="python", help="Logic substrate type")
    parser.add_argument("--output-dir", type=Path, default=Path("./deploy"), help="Where to save manifests")
    parser.add_argument("--project-id", default="my-sovereign-project", help="GCP Project ID")
    parser.add_argument("--region", default="us-central1", help="GCP Region")
    parser.add_argument("--replicas", type=int, default=3, help="Number of Sentinel pods for GKE")

    args = parser.parse_args()

    # Ensure output directory exists
    args.output_dir.mkdir(parents=True, exist_ok=True)

    image_url = f"gcr.io/{args.project_id}/{args.name}"

    # 1. Generate Dockerfile
    dockerfile_content = TEMPLATES[f"dockerfile_{args.type}"]
    dockerfile_path = args.output_dir / "Dockerfile"
    dockerfile_path.write_text(dockerfile_content)
    print(f"Created: {dockerfile_path}")

    # 2. Generate Cloud Run Service (Vulcan)
    cloud_run_content = TEMPLATES["cloud_run_yaml"].format(
        name=args.name,
        region=args.region,
        image_url=image_url,
        cpu="2",
        memory="4Gi"
    )
    cr_path = args.output_dir / "cloud-run.yaml"
    cr_path.write_text(cloud_run_content)
    print(f"Created: {cr_path}")

    # 3. Generate K8s Deployment (Sentinel Swarm)
    k8s_content = TEMPLATES["k8s_yaml"].format(
        name=args.name,
        image_url=image_url,
        replicas=args.replicas
    )
    k8s_path = args.output_dir / "k8s.yaml"
    k8s_path.write_text(k8s_content)
    print(f"Created: {k8s_path}")

    # 4. Create dummy requirements.txt if python
    if args.type == "python":
        req_path = args.output_dir / "requirements.txt"
        if not req_path.exists():
            req_path.write_text("fastapi\\nuvicorn\\nnumpy\\n")
            print(f"Created placeholder: {req_path}")

    print("\\nManifest generation complete. Ready for Cloud Build offloading.")

if __name__ == "__main__":
    main()